spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbspotmusic?
    useSSL=false&createDatabaseIfNotExist=true
    username: admin
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update